name: BERT_TaG

desc_encoder:
  _target_: source.encoder.BertEncoder.BertEncoder
  architecture: bert-base-uncased
  output_attentions: False
  pooling:
    _target_: source.pooling.NoPooling.NoPooling

code_encoder:
  _target_: source.encoder.BertEncoder.BertEncoder
  architecture: bert-base-uncased
  output_attentions: False
  pooling:
    _target_: source.pooling.NoPooling.NoPooling

hidden_size: 768

desc_tokenizer:
  architecture: ${model.desc_encoder.architecture}

code_tokenizer:
  architecture: ${model.code_encoder.architecture}

lr: 5e-5
desc_lr: 3e-6
code_lr: 3e-6
weight_decay: 1e-2

tag_training: True
desc_frequency_opt: 1
code_frequency_opt: 1

loss:
  _target_: source.loss.NTXentLoss.NTXentLoss
  params:
    name: NTXentLoss
    miner:
      relevance_map:
        dir: ${data.dir}
    criterion:
      temperature: 0.07

metric:
  relevance_map:
    dir: ${data.dir}
  num_nearest_neighbors: 10
  index: ${eval.index}