name: GPTNeo_CoTNG

desc_encoder:
  _target_: source.encoder.GPTNeoEncoder.GPTNeoEncoder
  architecture: EleutherAI/gpt-neo-125M
  output_attentions: False
  num_embeddings: 50258
  pad_id: 50257
  pooling:
    _target_: source.pooling.AveragePooling.AveragePooling

code_encoder:
  _target_: source.encoder.GPTNeoEncoder.GPTNeoEncoder
  architecture: EleutherAI/gpt-neo-125M
  output_attentions: False
  num_embeddings: 50258
  pad_id: 50257
  pooling:
    _target_: source.pooling.AveragePooling.AveragePooling

hidden_size: 768

desc_tokenizer:
  architecture: ${model.desc_encoder.architecture}
  pad: 50257

code_tokenizer:
  architecture: ${model.code_encoder.architecture}
  pad: 50257

lr: 5e-5
desc_lr: 5e-5
code_lr: 5e-5
base_lr: 5e-6
max_lr: 5e-3
weight_decay: 1e-2

co_training: True
desc_frequency_opt: 1
code_frequency_opt: 1

loss:
  _target_: source.loss.NPairsLoss.NPairsLoss
  params:
    name: N-Pair-Loss
