name: SelfAtt

desc_encoder:
  _target_: source.encoder.SelfAttEncoder.SelfAttEncoder
  vocabulary_size: ${model.vocabulary_size}
  representation_size: ${model.hidden_size}
  num_heads: 12
  dropout: 0.1
  pooling:
    _target_: source.pooling.AveragePooling.AveragePooling

code_encoder:
  _target_: source.encoder.SelfAttEncoder.SelfAttEncoder
  vocabulary_size: ${model.vocabulary_size}
  representation_size: ${model.hidden_size}
  num_heads: 12
  dropout: 0.1
  pooling:
    _target_: source.pooling.AveragePooling.AveragePooling

hidden_size: 768
vocabulary_size: 55000

desc_tokenizer:
  architecture: microsoft/codebert-base

code_tokenizer:
  architecture: microsoft/codebert-base

lr: 5e-5
desc_lr: 5e-5
code_lr: 5e-5
base_lr: 5e-6
max_lr: 5e-3
weight_decay: 1e-2

co_training: False
desc_frequency_opt: 1
code_frequency_opt: 1

loss:
  _target_: source.loss.NPairsLoss.NPairsLoss
  params:
    name: N-Pair-Loss